// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: grpcuser.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Describe string `protobuf:"bytes,5,opt,name=Describe,proto3" json:"Describe,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_grpcuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_grpcuser_proto_rawDescGZIP(), []int{0}
}

func (x *List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *List) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

type ResquestUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List *List `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *ResquestUser) Reset() {
	*x = ResquestUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcuser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResquestUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResquestUser) ProtoMessage() {}

func (x *ResquestUser) ProtoReflect() protoreflect.Message {
	mi := &file_grpcuser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResquestUser.ProtoReflect.Descriptor instead.
func (*ResquestUser) Descriptor() ([]byte, []int) {
	return file_grpcuser_proto_rawDescGZIP(), []int{1}
}

func (x *ResquestUser) GetList() *List {
	if x != nil {
		return x.List
	}
	return nil
}

type ResponseUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *List `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *ResponseUser) Reset() {
	*x = ResponseUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpcuser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUser) ProtoMessage() {}

func (x *ResponseUser) ProtoReflect() protoreflect.Message {
	mi := &file_grpcuser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUser.ProtoReflect.Descriptor instead.
func (*ResponseUser) Descriptor() ([]byte, []int) {
	return file_grpcuser_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUser) GetEvent() *List {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_grpcuser_proto protoreflect.FileDescriptor

var file_grpcuser_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x72, 0x70, 0x63, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0x3c, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3e, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x32, 0x69, 0x0a, 0x17, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x50, 0x62, 0x12, 0x4e, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12,
	0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpcuser_proto_rawDescOnce sync.Once
	file_grpcuser_proto_rawDescData = file_grpcuser_proto_rawDesc
)

func file_grpcuser_proto_rawDescGZIP() []byte {
	file_grpcuser_proto_rawDescOnce.Do(func() {
		file_grpcuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpcuser_proto_rawDescData)
	})
	return file_grpcuser_proto_rawDescData
}

var file_grpcuser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcuser_proto_goTypes = []interface{}{
	(*List)(nil),         // 0: proto_notification.List
	(*ResquestUser)(nil), // 1: proto_notification.ResquestUser
	(*ResponseUser)(nil), // 2: proto_notification.ResponseUser
}
var file_grpcuser_proto_depIdxs = []int32{
	0, // 0: proto_notification.ResquestUser.list:type_name -> proto_notification.List
	0, // 1: proto_notification.ResponseUser.event:type_name -> proto_notification.List
	1, // 2: proto_notification.NotificationInterfacePb.Verify:input_type -> proto_notification.ResquestUser
	2, // 3: proto_notification.NotificationInterfacePb.Verify:output_type -> proto_notification.ResponseUser
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcuser_proto_init() }
func file_grpcuser_proto_init() {
	if File_grpcuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpcuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcuser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResquestUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpcuser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpcuser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcuser_proto_goTypes,
		DependencyIndexes: file_grpcuser_proto_depIdxs,
		MessageInfos:      file_grpcuser_proto_msgTypes,
	}.Build()
	File_grpcuser_proto = out.File
	file_grpcuser_proto_rawDesc = nil
	file_grpcuser_proto_goTypes = nil
	file_grpcuser_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NotificationInterfacePbClient is the client API for NotificationInterfacePb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NotificationInterfacePbClient interface {
	Verify(ctx context.Context, in *ResquestUser, opts ...grpc.CallOption) (*ResponseUser, error)
}

type notificationInterfacePbClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationInterfacePbClient(cc grpc.ClientConnInterface) NotificationInterfacePbClient {
	return &notificationInterfacePbClient{cc}
}

func (c *notificationInterfacePbClient) Verify(ctx context.Context, in *ResquestUser, opts ...grpc.CallOption) (*ResponseUser, error) {
	out := new(ResponseUser)
	err := c.cc.Invoke(ctx, "/proto_notification.NotificationInterfacePb/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationInterfacePbServer is the server API for NotificationInterfacePb service.
type NotificationInterfacePbServer interface {
	Verify(context.Context, *ResquestUser) (*ResponseUser, error)
}

// UnimplementedNotificationInterfacePbServer can be embedded to have forward compatible implementations.
type UnimplementedNotificationInterfacePbServer struct {
}

func (*UnimplementedNotificationInterfacePbServer) Verify(context.Context, *ResquestUser) (*ResponseUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterNotificationInterfacePbServer(s *grpc.Server, srv NotificationInterfacePbServer) {
	s.RegisterService(&_NotificationInterfacePb_serviceDesc, srv)
}

func _NotificationInterfacePb_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResquestUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationInterfacePbServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_notification.NotificationInterfacePb/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationInterfacePbServer).Verify(ctx, req.(*ResquestUser))
	}
	return interceptor(ctx, in, info, handler)
}

var _NotificationInterfacePb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_notification.NotificationInterfacePb",
	HandlerType: (*NotificationInterfacePbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _NotificationInterfacePb_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcuser.proto",
}
