// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: test-notification.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type List struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Describe string `protobuf:"bytes,2,opt,name=Describe,proto3" json:"Describe,omitempty"`
}

func (x *List) Reset() {
	*x = List{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_notification_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *List) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*List) ProtoMessage() {}

func (x *List) ProtoReflect() protoreflect.Message {
	mi := &file_test_notification_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use List.ProtoReflect.Descriptor instead.
func (*List) Descriptor() ([]byte, []int) {
	return file_test_notification_proto_rawDescGZIP(), []int{0}
}

func (x *List) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *List) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

type ResquestNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List *List `protobuf:"bytes,1,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *ResquestNotification) Reset() {
	*x = ResquestNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_notification_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResquestNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResquestNotification) ProtoMessage() {}

func (x *ResquestNotification) ProtoReflect() protoreflect.Message {
	mi := &file_test_notification_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResquestNotification.ProtoReflect.Descriptor instead.
func (*ResquestNotification) Descriptor() ([]byte, []int) {
	return file_test_notification_proto_rawDescGZIP(), []int{1}
}

func (x *ResquestNotification) GetList() *List {
	if x != nil {
		return x.List
	}
	return nil
}

type ResponseNotificaiton struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event *List `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *ResponseNotificaiton) Reset() {
	*x = ResponseNotificaiton{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_notification_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseNotificaiton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseNotificaiton) ProtoMessage() {}

func (x *ResponseNotificaiton) ProtoReflect() protoreflect.Message {
	mi := &file_test_notification_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseNotificaiton.ProtoReflect.Descriptor instead.
func (*ResponseNotificaiton) Descriptor() ([]byte, []int) {
	return file_test_notification_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseNotificaiton) GetEvent() *List {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_test_notification_proto protoreflect.FileDescriptor

var file_test_notification_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x36, 0x0a,
	0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x14, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x69,
	0x74, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x32, 0x7d, 0x0a, 0x1b, 0x54, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x50, 0x62, 0x12, 0x5e, 0x0a, 0x06, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x28, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x52, 0x65, 0x73, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x28, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x69, 0x74, 0x6f, 0x6e,
	0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_test_notification_proto_rawDescOnce sync.Once
	file_test_notification_proto_rawDescData = file_test_notification_proto_rawDesc
)

func file_test_notification_proto_rawDescGZIP() []byte {
	file_test_notification_proto_rawDescOnce.Do(func() {
		file_test_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_notification_proto_rawDescData)
	})
	return file_test_notification_proto_rawDescData
}

var file_test_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_notification_proto_goTypes = []any{
	(*List)(nil),                 // 0: proto_notification.List
	(*ResquestNotification)(nil), // 1: proto_notification.ResquestNotification
	(*ResponseNotificaiton)(nil), // 2: proto_notification.ResponseNotificaiton
}
var file_test_notification_proto_depIdxs = []int32{
	0, // 0: proto_notification.ResquestNotification.list:type_name -> proto_notification.List
	0, // 1: proto_notification.ResponseNotificaiton.event:type_name -> proto_notification.List
	1, // 2: proto_notification.TestNotificationInterfacePb.Verify:input_type -> proto_notification.ResquestNotification
	2, // 3: proto_notification.TestNotificationInterfacePb.Verify:output_type -> proto_notification.ResponseNotificaiton
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_notification_proto_init() }
func file_test_notification_proto_init() {
	if File_test_notification_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_notification_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*List); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_notification_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResquestNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_notification_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseNotificaiton); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_notification_proto_goTypes,
		DependencyIndexes: file_test_notification_proto_depIdxs,
		MessageInfos:      file_test_notification_proto_msgTypes,
	}.Build()
	File_test_notification_proto = out.File
	file_test_notification_proto_rawDesc = nil
	file_test_notification_proto_goTypes = nil
	file_test_notification_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestNotificationInterfacePbClient is the client API for TestNotificationInterfacePb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestNotificationInterfacePbClient interface {
	Verify(ctx context.Context, in *ResquestNotification, opts ...grpc.CallOption) (*ResponseNotificaiton, error)
}

type testNotificationInterfacePbClient struct {
	cc grpc.ClientConnInterface
}

func NewTestNotificationInterfacePbClient(cc grpc.ClientConnInterface) TestNotificationInterfacePbClient {
	return &testNotificationInterfacePbClient{cc}
}

func (c *testNotificationInterfacePbClient) Verify(ctx context.Context, in *ResquestNotification, opts ...grpc.CallOption) (*ResponseNotificaiton, error) {
	out := new(ResponseNotificaiton)
	err := c.cc.Invoke(ctx, "/proto_notification.TestNotificationInterfacePb/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestNotificationInterfacePbServer is the server API for TestNotificationInterfacePb service.
type TestNotificationInterfacePbServer interface {
	Verify(context.Context, *ResquestNotification) (*ResponseNotificaiton, error)
}

// UnimplementedTestNotificationInterfacePbServer can be embedded to have forward compatible implementations.
type UnimplementedTestNotificationInterfacePbServer struct {
}

func (*UnimplementedTestNotificationInterfacePbServer) Verify(context.Context, *ResquestNotification) (*ResponseNotificaiton, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterTestNotificationInterfacePbServer(s *grpc.Server, srv TestNotificationInterfacePbServer) {
	s.RegisterService(&_TestNotificationInterfacePb_serviceDesc, srv)
}

func _TestNotificationInterfacePb_Verify_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ResquestNotification)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestNotificationInterfacePbServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto_notification.TestNotificationInterfacePb/Verify",
	}
	handler := func(ctx context.Context, req any) (any, error) {
		return srv.(TestNotificationInterfacePbServer).Verify(ctx, req.(*ResquestNotification))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestNotificationInterfacePb_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto_notification.TestNotificationInterfacePb",
	HandlerType: (*TestNotificationInterfacePbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Verify",
			Handler:    _TestNotificationInterfacePb_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test-notification.proto",
}
